# Generated by Django 4.2.8 on 2024-12-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_alter_song_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songgenres', to='tunaapi.genre'),
        ),
        migrations.AlterField(
            model_name='songgenre',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genresongs', to='tunaapi.song'),
        ),
    ]
