# Generated by Django 4.2.8 on 2024-12-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0003_alter_songgenre_genre_id_alter_songgenre_song_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
