# Generated by Django 4.2.8 on 2024-12-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0004_rename_artist_id_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songgenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='songgenre',
            old_name='song_id',
            new_name='song',
        ),
    ]
